theme: jekyll-theme-tactile
title: CS4641 Project: Predicting Stock Market Trends using Clustering and Regression Models
description: Anshul Agrawal, Alejandro Hernandez, Ty Parrillo, Edgar Urmanov, Zong-Rui Wee
